forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TextAreaField
from wtforms.validators import DataRequired
from wtforms.fields import FileField


class UploadPostForm(FlaskForm):
	title = StringField('Title', validators=[DataRequired()])
	content = TextAreaField('content',validators=[DataRequired()])
	image_name = StringField('image_name', validators=[DataRequired()])
	tags = StringField('tags', validators=[DataRequired()])
	description = TextAreaField('description', validators=[DataRequired()])

class UpdatePostForm(FlaskForm):
	title = StringField('Title', validators=[DataRequired()])
	content = TextAreaField('content',validators=[DataRequired()])
	image_name = StringField('image_name', validators=[DataRequired()])
	tags = StringField('tags', validators=[DataRequired()])
	description = TextAreaField('description', validators=[DataRequired()])

class LoginForm(FlaskForm):
	email = StringField('email', validators=[DataRequired()])
	password = PasswordField('password', validators=[DataRequired()])

class RegisterForm(FlaskForm):
	username = StringField('username', validators=[DataRequired()])
	email = StringField('email', validators=[DataRequired()])
	password = PasswordField('password', validators=[DataRequired()])

class UploadImageForm(FlaskForm):
	image = FileField('image', validators=[DataRequired()])

class UploadTag(FlaskForm):
	name = StringField('tag', validators=[DataRequired()])

modules/admin/blueprint.py
from flask import Blueprint

admin = Blueprint('admin', __name__, static_folder='assets', url_prefix='/admin/')

from . import views
from . import json

modules/admin/views.py
from flask import render_template, redirect, url_for, abort, flash, current_app
from pathlib import Path
from os import path
from .blueprint import admin
from forms import UploadPostForm, UploadImageForm, UploadTag
from database import Tags, Posts, db, Image
from flask_login import current_user, fresh_login_required
from uuid import uuid4

def save_file(doc, location):
	image_name = str(uuid4()) + '.jpg'

	with open(path.join(location, image_name), 'wb') as wfile:
		wfile.write(doc.read())

	return image_name

@admin.route('/')
@fresh_login_required
def homepage():
	return render_template('admin/homepage.html')


@admin.route('/upload/image', methods=['GET','POST'])
@fresh_login_required
def upload_image():
	form = UploadImageForm()

	if form.validate_on_submit():
		image = form.image.data

		current_app.logger.debug(image)

		image_name = save_file(image,Path(current_app.instance_path).parent.joinpath('static/img') )

		img = Image()
		img.name = image_name
		db.session.add(img)
		db.session.commit()

		current_app.logger.info(f'{image.name} saved to /static/images/')
		flash('image successfully uploaded', category='alert alert-success')
		return	 redirect(url_for('admin.homepage'))


	return render_template('admin/upload_image.html',form=form)


@admin.route('/upload/post', methods=['POST','GET'])
@fresh_login_required
def upload_post():
	form = UploadPostForm()
	if form.validate_on_submit():
		title = form.title.data.strip(' ')
		content = form.content.data.strip(' ')
		image_name = form.image_name.data.strip(' ')
		
		old = Posts.query.filter_by(title=title).first()
		if old:
			flash('post already collected')
			return redirect(url_for('admin.upload_post'))

		post = Posts(title=title, content=content)
		post.add_tag(form.tags.data)
		post.image_name = image_name
		post.description = form.description.data
		post.author = current_user

		db.session.add(post)
		db.session.commit()

		flash('upload successful')
		return redirect(url_for('admin.upload_post'))

	return render_template('admin/upload_post.html',form=form)

@admin.route('/upload/tag', methods=['POST','GET'])
@fresh_login_required
def upload_tag():
	form = UploadTag()

	if form.validate_on_submit():
		names = form.name.data.split(',')
		for name in names:
			tag = Tags.query.filter_by(name=name).first()
			if not tag:
				db.session.add(Tags(name=name))
				db.session.commit()

		flash('tags uploaded')

		return redirect(url_for('admin.upload_tag'))

	return render_template('admin/upload_tag.html', form=form)

from . import deletions
from . import json
from . import update
from . import login

modules/client/blueprint.py
from flask import Blueprint

client = Blueprint('client',__name__, static_folder='assets')

from . import views
from . import json

modules/client/views.py
from flask import render_template, redirect, request, url_for, current_app, Response
from .blueprint import client
from database import Posts, Tags
from flask import abort

@client.route('/')
def homepage():
    return render_template('index.html')

@client.route('/favicon.ico')
def favicon():
    with current_app.open_resource('modules/client/assets/favicon.png') as wfile:
        content = wfile.read()
        return Response(content, mimetype='image/png')

@client.route('/contact')
def contact():
    return render_template('contact.html')

@client.route('/tutorials')
def tutorials():
    section_name = request.args.get('section')
    section = Tags.query.filter_by(name=section_name).first()

    page = request.args.get('page', 1, type=int)

    if not section:
        abort(404)

    pagination = Posts.query.filter(Posts.tags.any(name=section_name)).order_by(Posts.date.desc()).paginate(page=page, per_page=7, error_out=False)
    posts = pagination.items

    if not posts:
        abort(404)

    related_posts = []

    related_python = Posts.query.filter(Posts.tags.any(name='flask'))
    if related_python:
        related_posts.append(related_python.paginate(page=1, per_page=2).items)

    related_biology = Posts.query.filter(Posts.tags.any(name='biology'))
    if related_biology:
        related_posts.append(related_biology.paginate(page=1, per_page=2).items)

    tag_cloud = Tags.query.paginate(page=1, per_page=15, error_out=False).items

    return render_template('blog.html', posts=posts, others=related_posts, tag_cloud=tag_cloud)

@client.route('/tutorials/<title>')
def tutorials_read(title):
    post = Posts.query.filter_by(title=title).first()
    if not post:
        abort(404)

    related_posts = Posts.query.filter(Posts.tags.any(name=post.tags[0].name)).filter(Posts.id != post.id).paginate(page=1, per_page=4, error_out=False).items
    tag_cloud = Tags.query.paginate(page=1, per_page=15, error_out=False).items

    return render_template('blog-details.html', post=post, others=related_posts, tag_cloud=tag_cloud)

@client.app_errorhandler(404)
def file_not_found(e):
    return render_template('404.html'), 404

templates/addons.html
{% macro navigation() %}

<nav class="navbar navbar-expand-lg navbar-light navbar-floating">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="{{url_for('client.static',filename='favicon.png')}}" alt="" width="40">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarToggler">
      <ul class="navbar-nav ml-lg-5 mt-3 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('client.tutorials',section='flask')}}
          ">Flask</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('client.tutorials',section='biology')}}">Biology</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('client.tutorials',section='chemistry')}}">Chemistry</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="/contact">Contact</a>
        </li>
       <!-- <li class="nav-item">
          <a class="nav-link" href="#">PDF Documents</a>
        </li> -->
      </ul>
    </div>
  </div>
</nav>

{% endmacro %}

{% macro links() %}
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Biotonic</title>

  <link rel="shortcut icon" href="{{url_for('client.static',filename='favicon.png')}}" type="image/x-icon">

  <link rel="stylesheet" href="{{url_for('client.static',filename='css/maicons.css')}}">

  <link rel="stylesheet" href="{{url_for('client.static',filename='vendor/animate/animate.css')}}">

  <link rel="stylesheet" href="{{url_for('client.static',filename='vendor/owl-carousel/css/owl.carousel.min.css')}}">

  <link rel='stylesheet' href='{{url_for("client.static",filename="css/all.css")}}'>

  <link rel="stylesheet" href="{{url_for('client.static',filename='css/bootstrap.css')}}">

  <link rel="stylesheet" href="{{url_for('client.static',filename='css/mobster.css')}}">
 {% endmacro %}

 {% macro footer() %}
 <footer class='bg-dark text-center text-muted'>
	<p class='mb-0'> Keep learning </p>
</footer>
{% endmacro %}

templates/blog-details.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% from 'addons.html' import links %}
  {{links()}}
  <meta name='description' content='{{post.description}}'>
  
</head>
<body>
{% from 'addons.html' import navigation %}
    {{navigation()}}  
<main>


  <div class="page-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 py-3">
          <article class="blog-single-entry">
            <div class="post-thumbnail">
              <img src="/static/img/{{post.image_name}}" style=' ' alt="" >
            </div>
            <div class="post-date">
              Posted on <a href="#">{{post.date.strftime('%d-%m-%Y')}}</a>
            </div>
            <h1 class="post-title">{{post.title}}</h1>
            <div class="entry-meta mb-4">
              <div class="meta-item entry-author">
                <div class="icon">
                  <span class="mai-person"></span>  
                </div>
                by <a href="#">{{post.author.username}}</a>
              </div>
              <div class="meta-item">
                <div class="icon">
                  <span class="mai-pricetags"></span>
                </div>
                Category: 
                {% for tag in post.tags %}
                <a href='/tutorials?section={{tag.name}}'>{{tag.name}}</a>,
                {% endfor %}
              </div>
              <!--<div class="meta-item">
                <div class="icon">
                  <span class="mai-chatbubble-ellipses"></span>
                </div>
                 <a href="#">24 Comments</a> 
              </div>-->
            </div>
            <div class="entry-content">
              {{post.content | safe}}
            </div>
          </article>

          <!-- end -->
          <!-- Comments -->
          
        </div>

        <!-- Sidebar -->
        <div class="col-lg-4 py-3">
          <div class="widget-wrap">
            <form action="{{url_for('client.tutorials')}}" class="search-form">
              <h3 class="widget-title">Search</h3>
              <div class="form-group">
                <span class="icon mai-search"></span>
                <input type="text" class="form-control" name='section' placeholder="Type a keyword and hit enter">
              </div>
            </form>
          </div>

            <div class="widget-wrap">
              <h3 class="widget-title">Recent Blog</h3>
              {% for other in others %}
              <div class="blog-widget">
                <div class="blog-img">
                  <img src="/static/img/{{other.image_name}}" alt="">
                </div>
                <div class="entry-footer">
                  <div class="blog-title mb-2"><a href="/tutorials/{{other.title}}">{{other.description}}</a></div>
                  <div class="meta">
                    <a href="#"><span class="icon-calendar"></span>{{other.date.strftime('%d-%m-%Y')}}</a>
                    <a href="#"><span class="icon-person"></span>{{other.author.username}}</a>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>

          <div class="widget-wrap">
            <h3 class="widget-title">Tag Cloud</h3>
            <div class="tag-clouds">
              {% for tags in tag_cloud %}
              <a href="{{url_for('client.tutorials',section=tags.name)}}" class="tag-cloud-link">{{tags.name}}</a>
              {% endfor %}
            </div>
          </div>
        </div> <!-- end sidebar -->

      </div> <!-- .row -->
    </div>
  </div>

</main>


{% from 'addons.html' import footer %}
{{footer()}}


<script src="../assets/js/jquery-3.5.1.min.js"></script>

<script src="../assets/js/bootstrap.bundle.min.js"></script>

<script src="../assets/vendor/owl-carousel/js/owl.carousel.min.js"></script>

<script src="../assets/vendor/wow/wow.min.js"></script>

<script src="../assets/js/mobster.js"></script>

</body>
</html>

templates/blog.html
<!DOCTYPE html>
<html lang="en">
<head> 
  {% from 'addons.html' import links %}
  {{links()}}
  
</head>
<body>
{% from 'addons.html' import navigation %}
    {{navigation()}}  
<main>


  <div class="page-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 py-3">
          {% for post in posts %}
            <article class="blog-entry">
              <div class="entry-header">
                <div class="post-thumbnail">
                  <img src="/static/img/{{post.image_name}}" alt="">
                </div>
                <div class="post-date">
                  <h3>{{post.date.day}}</h3>
                  <span>{{post.date.ctime().split(' ')[1]}}</span>
                </div>
              </div>
              <div class="post-title"><a href="blog-details.html">{{post.title}}</a></div>
              <div class="entry-meta mb-2">
                <div class="meta-item entry-author">
                  <div class="icon">
                    <span class="mai-person"></span>  
                  </div>
                  by <a href="#">{{post.author.username}}</a>
                </div>
                <div class="meta-item">
                  <div class="icon">
                    <span class="mai-pricetags"></span>
                  </div>
                  Category: 
                  {% for tag in post.tags %}
                    <a href="#">{{tag.name}},</a>
                  {% endfor %}
                </div>
                <!-- <div class="meta-item">
                  <div class="icon">
                    <span class="mai-chatbubble-ellipses"></span>
                  </div>
                  <a href="#">24 Comments</a>
                </div> -->
              </div>
              <div class="entry-content">
                <p>{{post.description}}</p>
              </div>
              <a href="/tutorials/{{post.title}}" class="btn btn-primary">Continue Reading</a>
            </article>
            {% endfor %}
        </div>
        <!-- Sidebar -->
        <div class="col-lg-4 py-3">
          <div class="widget-wrap">
            <form action='{{url_for("client.tutorials")}}' class="search-form">
              <h3 class="widget-title">Search</h3>
              <div class="form-group">
                <span class="icon mai-search"></span>
                <input type="text" class="form-control" name='section' placeholder="Type a keyword and hit enter">
              </div>
            </form>
          </div>

          <div class="widget-wrap">
            <h3 class="widget-title">Tag Cloud</h3>
            <div class="tag-clouds">
              {% for tags in tag_cloud %}
              <a href="{{url_for('client.tutorials',section=tags.name)}}" class="tag-cloud-link">{{tags.name}}</a>
              {% endfor %}
            </div>
          </div>
        </div> <!-- end sidebar -->
      </div>
    </div>
  </div>

</main>


 {% from 'addons.html' import footer %}
{{footer()}}


<script src="../assets/js/jquery-3.5.1.min.js"></script>

<script src="../assets/js/bootstrap.bundle.min.js"></script>

<script src="../assets/vendor/owl-carousel/js/owl.carousel.min.js"></script>

<script src="../assets/vendor/wow/wow.min.js"></script>

<script src="../assets/js/mobster.js"></script>

</body>
</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
 {% from 'addons.html' import links %}
  {{links()}}
</head>
<body>
  {% from 'addons.html' import navigation %}
    {{navigation()}}
    
<div class="bg-light">

<div class="page-section">
  <div class="container">
      <div class="row">
        <div class="col-lg-7 py-3 mb-5 mb-lg-0">
          <div class="img-place w-lg-75 wow zoomIn">
            <img src="/static/img/illustration_contact.svg" alt="">
          </div>
        </div>
        <div class="col-lg-5 py-3">
          <h1 class="wow fadeInUp">Need a help? <br>
          Don't worry just contact us</h1>

          <form method="POST" class="mt-5" action="mailto:chembio451@gmail.com">
            <div class="form-group wow fadeInUp">
              <label for="name" class="fw-medium fg-grey">Fullname</label>
              <input type="text" class="form-control" id="name">
            </div>

            <div class="form-group wow fadeInUp">
              <label for="email" class="fw-medium fg-grey">Email</label>
              <input type="text" class="form-control" id="email">
            </div>

            <div class="form-group wow fadeInUp">
              <label for="message" class="fw-medium fg-grey">Message</label>
              <textarea rows="6" class="form-control" id="message"></textarea>
            </div>

            <div class="form-group mt-4 wow fadeInUp">
              <button type="submit" class="btn btn-primary">Send Message</button>
            </div>
          </form>
        </div>
      </div>
  </div>
</div>
<script src="../assets/js/jquery-3.5.1.min.js"></script>

<script src="../assets/js/bootstrap.bundle.min.js"></script>

<script src="../assets/vendor/owl-carousel/js/owl.carousel.min.js"></script>

<script src="../assets/vendor/wow/wow.min.js"></script>

<script src="../assets/js/mobster.js"></script>

<script src="../assets/js/google-maps.js"></script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAIA_zqjFMsJM_sxP9-6Pde5vVCTyJmUHM&callback=initMap"></script>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name='description' content='Learn the fundamentals of biology'>

   {% from 'addons.html' import links %}
  {{links()}}
</head>
<body>
  {% from 'addons.html' import navigation %}
    {{navigation()}}
  
<div class="page-hero-section bg-image hero-home-1" style="background-image: url('/static/img/bg_hero_1.svg')}});">
  <div class="hero-caption pt-5">
    <div class="container h-100">
      <div class="row align-items-center h-100">
        <div class="col-lg-6 wow fadeInUp">
          <div class="badge mb-2"><span class="icon mr-1"><span class="mai-globe"></span></span>The students guide to Biology</div>
          <h1 class="mb-4">Study biology with the aid of biotonic</h1>
          <p class="mb-4">Learn biology when you want and how you what.</p>
          <a href="/tutorials?section=biology" class="btn btn-primary rounded-pill" title='learn biology'>Learn Biology</a>
        </div>
        <div class="col-lg-6 d-none d-lg-block wow zoomIn">
          <div class="img-place mobile-preview shadow floating-animate">
            <img src="/static/img/biology.jpg"  style='height: 100%;'alt="">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="position-realive bg-image" style="background-image: url(/static/img/pattern_1.svg);">

<div class="page-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 py-3">
        <div class="img-place mobile-preview shadow wow zoomIn">
          <img src="/static/img/app_preview_2.png" alt="">
        </div>
      </div>
      <div class="col-lg-6 py-3 mt-lg-5">
        <div class="iconic-list">
          <div class="iconic-item wow fadeInUp">
            <div class="iconic-md iconic-text bg-warning fg-white rounded-circle">
              <span class="fa fa-lg fa-tablet-alt"></span>
            </div>
            <div class="iconic-content">
              <h5>Simple Explanations</h5>
              <p class="fs-small">Explanation of concepts are simple for quick and better understanding</p>
            </div>
          </div>
          <div class="iconic-item wow fadeInUp">
            <div class="iconic-md iconic-text bg-info fg-white rounded-circle">
              <span class="fa fa-photo-video fa-lg"></span>
            </div>
            <div class="iconic-content">
              <h5>Pictographs of phenomena</h5>
              <p class="fs-small">Phenomena such as water cycle and nutrient cycle are represented in with pictures</p>
            </div>
          </div>
          <div class="iconic-item wow fadeInUp">
            <div class="iconic-md iconic-text bg-indigo fg-white rounded-circle">
              <span class="fa fa-lg fa-plane-departure"></span>
            </div>
            <div class="iconic-content">
              <h5>Progressive nature</h5>
              <p class="fs-small">Check your progress by taking the quiz that follows each topic</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="page-section bg-image bg-image-overlay-dark" style="background-image: url('/static/img/bg_testimonials.jpg');">
  <div class="container fg-white">
    <div class="row">
      <div class="col-md-8 col-lg-6 offset-lg-1 wow fadeInUp">
        <h2 class="mb-5 fg-white fw-normal">Python3 Programming Lessons</h2>
        <p class="fs-large font-italic">Biotonic offers lesson on python programming for website development. If you are
        a lover of computers and programmers, you can take on this course and learn how to build websites.</p>
        <p class="fs-large fg-grey fw-medium mb-5">-- Dev Seth Ikiroma-Owiye</p>

        <a href="/tutorials?section=flask" title='Learn website creation with python3' class="btn btn-outline-light rounded-pill">Learn website building with python3<span class="mai-chevron-forward"></span></a>
      </div>
    </div>
  </div>
</div>


<div class="page-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-7 py-3 mb-5 mb-lg-0">
        <div class="img-place w-lg-75 wow zoomIn">
          <img src="/static/img/illustration_contact.svg" alt="">
        </div>
      </div>
      <div class="col-lg-5 py-3">
        <h1 class="wow fadeInUp">Need a help? <br>
        Don't worry just contact us</h1>

        <form method="POST" class="mt-5" action="mailto:chembio451@gmail.com">
          <div class="form-group wow fadeInUp">
            <label for="name" class="fw-medium fg-grey">Fullname</label>
            <input type="text" class="form-control" id="name">
          </div>

          <div class="form-group wow fadeInUp">
            <label for="email" class="fw-medium fg-grey">Email</label>
            <input type="text" class="form-control" id="email">
          </div>

          <div class="form-group wow fadeInUp">
            <label for="message" class="fw-medium fg-grey">Message</label>
            <textarea rows="6" class="form-control" id="message"></textarea>
          </div>

          <div class="form-group mt-4 wow fadeInUp">
            <button type="submit" class="btn btn-primary">Send Message</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% from 'addons.html' import footer %}
{{footer()}}

<script src="{{url_for('client.static',filename='js/jquery-3.5.1.min.js')}}"></script>

<script src="{{url_for('client.static',filename='js/bootstrap.bundle.min.js')}}"></script>

<script src="{{url_for('client.static',filename='vendor/owl-carousel/js/owl.carousel.min.js')}}"></script>

<script src="{{url_for('client.static',filename='vendor/wow/wow.min.js')}}"></script>

<script src="{{url_for('client.static',filename='js/mobster.js')}}"></script>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
        }

        form {
            display: flex;
            flex-direction: column;
            width: 300px;
            margin: 0 auto;
        }

        label {
            margin-bottom: 5px;
            display: block;
        }

        input[type="text"],
        input[type="password"] {
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
            margin-bottom: 15px;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        .message {
            color: red;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <form method='POST'>
        {% for field in form %}
            <label for="{{ field.name }}">{{ field.label }}</label>
            {{field(size=30, placeholder=field.name)}}
        {% endfor %}
        <input type='submit' value='Login'>
    </form>

    <p class="message">
        {% for message in get_flashed_messages() %}
            {{message}}
        {% endfor %}
      </p>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Register</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
        }

        form {
            display: flex;
            flex-direction: column;
            width: 300px;
            margin: 0 auto;
        }

        label {
            margin-bottom: 5px;
            display: block;
        }

        input[type="text"],
        input[type="password"] {
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
            margin-bottom: 15px;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        .message {
            color: red;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <form method='POST'>
        {% for field in form %}
            <label for="{{ field.name }}">{{ field.label }}</label>
            {{field(size=30, placeholder=field.name)}}
        {% endfor %}
        <input type='submit' value='Register'>
    </form>

    <p class="message">
        {% for message in get_flashed_messages() %}
            {{message}}
        {% endfor %}
      </p>
</body>
</html>